### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by PhanaticD** [jb-aero/CHTag#3]
bind(player_tagged, null, null, @e,
  console(@e)
  msg(@e)
  modify_event('tag', color(c) . @e['tag'])
)

No console output, and no color tag

tried with itag 22 http://www.spigotmc.org/resources/itag.342/
protocollib 117 http://ci.shadowvolt.com/job/ProtocolLib/

using CH build 2886 and chtag build 2

**Comment by jb-aero** [comment]
If it's something I'm doing, they've done nothing to indicate things have changed.

**Comment by PhanaticD** [comment]
well other plugins still do work for example http://dev.bukkit.org/bukkit-plugins/nametags/ so I dont think the tag api itself change/broke

**Comment by PhanaticD** [comment]
https://github.com/PhanaticD/CHTag/commit/87910abe575d7c55a0dde996d4316e038a6b695a

**Comment by jb-aero** [comment]
Fixed by #4
